"""Deterministic administrative gazetteer and place dictionary for India."""

from typing import Any, Dict, List

# 1. Indian States & Union Territories (Region-level entities: NO point coordinates)
INDIAN_STATES: Dict[str, Dict[str, Any]] = {
    "maharashtra": {"state": "Maharashtra"},
    "karnataka": {"state": "Karnataka"},
    "tamil nadu": {"state": "Tamil Nadu"},
    "delhi": {"state": "Delhi"},
    "kerala": {"state": "Kerala"},
    "assam": {"state": "Assam"},
    "west bengal": {"state": "West Bengal"},
    "gujarat": {"state": "Gujarat"},
    "odisha": {"state": "Odisha"},
    "uttar pradesh": {"state": "Uttar Pradesh"},
    "telangana": {"state": "Telangana"},
    "andhra pradesh": {"state": "Andhra Pradesh"},
    "bihar": {"state": "Bihar"},
    "rajasthan": {"state": "Rajasthan"},
    "madhya pradesh": {"state": "Madhya Pradesh"},
    "punjab": {"state": "Punjab"},
    "haryana": {"state": "Haryana"},
    "himachal pradesh": {"state": "Himachal Pradesh"},
    "uttarakhand": {"state": "Uttarakhand"},
    "jammu and kashmir": {"state": "Jammu and Kashmir"},
    "goa": {"state": "Goa"},
    "jharkhand": {"state": "Jharkhand"},
    "chhattisgarh": {"state": "Chhattisgarh"},
    "tripura": {"state": "Tripura"},
    "meghalaya": {"state": "Meghalaya"},
    "manipur": {"state": "Manipur"},
    "nagaland": {"state": "Nagaland"},
    "sikkim": {"state": "Sikkim"},
    "arunachal pradesh": {"state": "Arunachal Pradesh"},
    "mizoram": {"state": "Mizoram"},
    "puducherry": {"state": "Puducherry"},
    "chandigarh": {"state": "Chandigarh"},
    "ladakh": {"state": "Ladakh"},
}

# 2. Major Cities & Districts with parent State & verified coordinates
INDIAN_CITIES: Dict[str, Dict[str, Any]] = {
    "mumbai": {
        "city": "Mumbai",
        "district": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.0760,
        "lon": 72.8777,
    },
    "bombay": {
        "city": "Mumbai",
        "district": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.0760,
        "lon": 72.8777,
    },
    "bengaluru": {
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9716,
        "lon": 77.5946,
    },
    "bangalore": {
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9716,
        "lon": 77.5946,
    },
    "delhi": {
        "city": "Delhi",
        "district": "New Delhi",
        "state": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
    },
    "new delhi": {
        "city": "New Delhi",
        "district": "New Delhi",
        "state": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
    },
    "chennai": {
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0827,
        "lon": 80.2707,
    },
    "madras": {
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0827,
        "lon": 80.2707,
    },
    "kolkata": {
        "city": "Kolkata",
        "district": "Kolkata",
        "state": "West Bengal",
        "lat": 22.5726,
        "lon": 88.3639,
    },
    "calcutta": {
        "city": "Kolkata",
        "district": "Kolkata",
        "state": "West Bengal",
        "lat": 22.5726,
        "lon": 88.3639,
    },
    "hyderabad": {
        "city": "Hyderabad",
        "district": "Hyderabad",
        "state": "Telangana",
        "lat": 17.3850,
        "lon": 78.4867,
    },
    "pune": {
        "city": "Pune",
        "district": "Pune",
        "state": "Maharashtra",
        "lat": 18.5204,
        "lon": 73.8567,
    },
    "ahmedabad": {
        "city": "Ahmedabad",
        "district": "Ahmedabad",
        "state": "Gujarat",
        "lat": 23.0225,
        "lon": 72.5714,
    },
    "jaipur": {
        "city": "Jaipur",
        "district": "Jaipur",
        "state": "Rajasthan",
        "lat": 26.9124,
        "lon": 75.7873,
    },
    "lucknow": {
        "city": "Lucknow",
        "district": "Lucknow",
        "state": "Uttar Pradesh",
        "lat": 26.8467,
        "lon": 80.9462,
    },
    "patna": {
        "city": "Patna",
        "district": "Patna",
        "state": "Bihar",
        "lat": 25.5941,
        "lon": 85.1376,
    },
    "guwahati": {
        "city": "Guwahati",
        "district": "Kamrup Metropolitan",
        "state": "Assam",
        "lat": 26.1445,
        "lon": 91.7362,
    },
    "surat": {
        "city": "Surat",
        "district": "Surat",
        "state": "Gujarat",
        "lat": 21.1702,
        "lon": 72.8311,
    },
    "kochi": {
        "city": "Kochi",
        "district": "Ernakulam",
        "state": "Kerala",
        "lat": 9.9312,
        "lon": 76.2673,
    },
    "bhubaneswar": {
        "city": "Bhubaneswar",
        "district": "Khurda",
        "state": "Odisha",
        "lat": 20.2961,
        "lon": 85.8245,
    },
    "yadgir": {
        "city": "Yadgir",
        "district": "Yadgir",
        "state": "Karnataka",
        "lat": 16.7375,
        "lon": 77.1253,
    },
    "wayanad": {
        "city": "Kalpetta",
        "district": "Wayanad",
        "state": "Kerala",
        "lat": 11.6854,
        "lon": 76.1320,
    },
    "srinagar": {
        "city": "Srinagar",
        "district": "Srinagar",
        "state": "Jammu and Kashmir",
        "lat": 34.0837,
        "lon": 74.7973,
    },
    "shimla": {
        "city": "Shimla",
        "district": "Shimla",
        "state": "Himachal Pradesh",
        "lat": 31.1048,
        "lon": 77.1734,
    },
    "dehradun": {
        "city": "Dehradun",
        "district": "Dehradun",
        "state": "Uttarakhand",
        "lat": 30.3165,
        "lon": 78.0322,
    },
    "thane": {
        "city": "Thane",
        "district": "Thane",
        "state": "Maharashtra",
        "lat": 19.2183,
        "lon": 72.9781,
    },
    "visakhapatnam": {
        "city": "Visakhapatnam",
        "district": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "lat": 17.6868,
        "lon": 83.2185,
    },
}

# 3. Known Localities & Sub-areas with parent city, state, and verified coordinates
INDIAN_LOCALITIES: Dict[str, Dict[str, Any]] = {
    # Mumbai Localities
    "andheri": {
        "locality": "Andheri",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.1197,
        "lon": 72.8468,
    },
    "andheri station": {
        "locality": "Andheri",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.1197,
        "lon": 72.8468,
    },
    "kurla": {
        "locality": "Kurla",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.0726,
        "lon": 72.8845,
    },
    "sion": {
        "locality": "Sion",
        "city": "Mumbai",
        "district": "Mumbai City",
        "state": "Maharashtra",
        "lat": 19.0390,
        "lon": 72.8619,
    },
    "bandra": {
        "locality": "Bandra",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.0596,
        "lon": 72.8295,
    },
    "dadar": {
        "locality": "Dadar",
        "city": "Mumbai",
        "district": "Mumbai City",
        "state": "Maharashtra",
        "lat": 19.0178,
        "lon": 72.8478,
    },
    "borivali": {
        "locality": "Borivali",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.2307,
        "lon": 72.8567,
    },
    "juhu": {
        "locality": "Juhu",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.1075,
        "lon": 72.8263,
    },
    "worli": {
        "locality": "Worli",
        "city": "Mumbai",
        "district": "Mumbai City",
        "state": "Maharashtra",
        "lat": 19.0166,
        "lon": 72.8166,
    },
    "chembur": {
        "locality": "Chembur",
        "city": "Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "lat": 19.0522,
        "lon": 72.8995,
    },
    # Bengaluru Localities
    "indiranagar": {
        "locality": "Indiranagar",
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9784,
        "lon": 77.6408,
    },
    "koramangala": {
        "locality": "Koramangala",
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9352,
        "lon": 77.6245,
    },
    "whitefield": {
        "locality": "Whitefield",
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9698,
        "lon": 77.7500,
    },
    "jayanagar": {
        "locality": "Jayanagar",
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 12.9308,
        "lon": 77.5838,
    },
    "hebbal": {
        "locality": "Hebbal",
        "city": "Bengaluru",
        "district": "Bengaluru Urban",
        "state": "Karnataka",
        "lat": 13.0358,
        "lon": 77.5970,
    },
    # Delhi Localities
    "connaught place": {
        "locality": "Connaught Place",
        "city": "New Delhi",
        "district": "New Delhi",
        "state": "Delhi",
        "lat": 28.6315,
        "lon": 77.2167,
    },
    "rohini": {
        "locality": "Rohini",
        "city": "Delhi",
        "district": "North West Delhi",
        "state": "Delhi",
        "lat": 28.7495,
        "lon": 77.0565,
    },
    "lajpat nagar": {
        "locality": "Lajpat Nagar",
        "city": "New Delhi",
        "district": "South Delhi",
        "state": "Delhi",
        "lat": 28.5677,
        "lon": 77.2433,
    },
    "dwarka": {
        "locality": "Dwarka",
        "city": "Delhi",
        "district": "South West Delhi",
        "state": "Delhi",
        "lat": 28.5921,
        "lon": 77.0460,
    },
    # Chennai Localities
    "t nagar": {
        "locality": "T. Nagar",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0418,
        "lon": 80.2341,
    },
    "velachery": {
        "locality": "Velachery",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "lat": 12.9815,
        "lon": 80.2180,
    },
    "adyar": {
        "locality": "Adyar",
        "city": "Chennai",
        "district": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0012,
        "lon": 80.2565,
    },
}

# 4. Ambiguous place names with multiple distinct geographic candidates across states
AMBIGUOUS_PLACES: Dict[str, List[Dict[str, Any]]] = {
    "rajpur": [
        {
            "place_name": "Rajpur (Dehradun)",
            "locality": "Rajpur",
            "district": "Dehradun",
            "state": "Uttarakhand",
            "lat": 30.3833,
            "lon": 78.0833,
        },
        {
            "place_name": "Rajpur (Barwani)",
            "city": "Rajpur",
            "district": "Barwani",
            "state": "Madhya Pradesh",
            "lat": 21.9333,
            "lon": 75.1333,
        },
        {
            "place_name": "Rajpur (Balrampur)",
            "city": "Rajpur",
            "district": "Balrampur",
            "state": "Chhattisgarh",
            "lat": 23.5333,
            "lon": 83.3333,
        },
    ],
    "bilaspur": [
        {
            "place_name": "Bilaspur (Chhattisgarh)",
            "city": "Bilaspur",
            "district": "Bilaspur",
            "state": "Chhattisgarh",
            "lat": 22.0797,
            "lon": 82.1391,
        },
        {
            "place_name": "Bilaspur (Himachal Pradesh)",
            "city": "Bilaspur",
            "district": "Bilaspur",
            "state": "Himachal Pradesh",
            "lat": 31.3326,
            "lon": 76.7606,
        },
    ],
    "rampur": [
        {
            "place_name": "Rampur (Uttar Pradesh)",
            "city": "Rampur",
            "district": "Rampur",
            "state": "Uttar Pradesh",
            "lat": 28.8154,
            "lon": 79.0257,
        },
        {
            "place_name": "Rampur (Shimla)",
            "city": "Rampur",
            "district": "Shimla",
            "state": "Himachal Pradesh",
            "lat": 31.4484,
            "lon": 77.6321,
        },
    ],
    "aurangabad": [
        {
            "place_name": "Chhatrapati Sambhaji Nagar (Aurangabad)",
            "city": "Chhatrapati Sambhaji Nagar",
            "district": "Chhatrapati Sambhaji Nagar",
            "state": "Maharashtra",
            "lat": 19.8762,
            "lon": 75.3433,
        },
        {
            "place_name": "Aurangabad (Bihar)",
            "city": "Aurangabad",
            "district": "Aurangabad",
            "state": "Bihar",
            "lat": 24.7500,
            "lon": 84.3700,
        },
    ],
}

# 5. Recognized Foreign Locations (Country entities have NO point coordinates)
FOREIGN_LOCATIONS: Dict[str, Dict[str, Any]] = {
    # Foreign Country Regions (NO point coordinates)
    "nepal": {"place_name": "Nepal", "country": "Nepal", "lat": None, "lon": None},
    "bangladesh": {
        "place_name": "Bangladesh",
        "country": "Bangladesh",
        "lat": None,
        "lon": None,
    },
    "sri lanka": {
        "place_name": "Sri Lanka",
        "country": "Sri Lanka",
        "lat": None,
        "lon": None,
    },
    "germany": {"place_name": "Germany", "country": "Germany", "lat": None, "lon": None},
    # Specific Foreign Cities (Point coordinates preserved with foreign country)
    "kathmandu": {
        "place_name": "Kathmandu",
        "city": "Kathmandu",
        "country": "Nepal",
        "lat": 27.7172,
        "lon": 85.3240,
    },
    "pokhara": {
        "place_name": "Pokhara",
        "city": "Pokhara",
        "country": "Nepal",
        "lat": 28.2096,
        "lon": 83.9856,
    },
    "rasuwa": {
        "place_name": "Rasuwa",
        "district": "Rasuwa",
        "country": "Nepal",
        "lat": 28.1458,
        "lon": 85.2974,
    },
    "dhaka": {
        "place_name": "Dhaka",
        "city": "Dhaka",
        "country": "Bangladesh",
        "lat": 23.8103,
        "lon": 90.4125,
    },
    "colombo": {
        "place_name": "Colombo",
        "city": "Colombo",
        "country": "Sri Lanka",
        "lat": 6.9271,
        "lon": 79.8612,
    },
    "berlin": {
        "place_name": "Berlin",
        "city": "Berlin",
        "country": "Germany",
        "lat": 52.5200,
        "lon": 13.4050,
    },
}
